name: DemoCustomDockerAction

on:
  workflow_dispatch:
jobs:
  demo-custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Call Demo action
        id: call-demo
        uses: dk521123/hello-world-docker-action@1bba80655c8b8611af37da21c5fc56e155ce4c42
        with:
          input_id1: 'Hello world!!!?'
      - name: Show result
        run: |
          echo ${{ env.output_id1 }}
        env:
          output_id1: ${{ steps.call-demo.outputs.output_id1 }}
